name: Versioning and Release

on:
  push:
    branches:
      - main

jobs:
  update_version_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name "Joseph Chu"
          git config --global user.email "karkinoscode@gmail.com"

      - name: Update version
        id: versioning
        run: |
          # Extract commit message
          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.sha }})

          # Check if the commit message contains 'major' or 'minor'
          if [[ $COMMIT_MSG == *"major"* ]]; then
            # Increment major version
            npm version major
          elif [[ $COMMIT_MSG == *"minor"* ]]; then
            # Increment minor version
            npm version minor
          else
            echo "No version increment needed"
            exit 0  # Exit early if no version increment is needed
          fi

          # Capture the updated version number
          UPDATED_VERSION=$(node -p "require('./package.json').version")

          # Create a new tag for the latest version
          git tag -a $UPDATED_VERSION -m "Tagging version $UPDATED_VERSION"
          git push origin $UPDATED_VERSION

          # Output the updated version for later steps
          echo "::set-output name=updated_version::$UPDATED_VERSION"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.updated_version }}
          release_name: Release ${{ steps.versioning.outputs.updated_version }}
          draft: false
          prerelease: false
